name: Build and Release APK on Github

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Decode keystore
        run: |
          echo "${{ secrets.ANDROID_GITHUB_KEYSTORE_BASE64 }}" | base64 --decode > android/app/upload-keystore.jks

      - name: Create key.properties
        run: |
          echo "storeFile=upload-keystore.jks" >> android/key.properties
          echo "storePassword=${{ secrets.ANDROID_KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_KEY_ALIAS }}" >> android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_KEY_PASSWORD }}" >> android/key.properties

      - name: Prepare GitHub Flavor
        run: ./scripts/prepare_flavor.sh github

      - name: Build GitHub APK
        run: flutter build apk --flavor github --target-platform=android-arm64 --release

      - name: Rename APK
        run: |
          mkdir -p apks
          cp build/app/outputs/flutter-apk/app-github-release.apk apks/sample-app-arm64-v8a-${{ github.ref_name }}.apk

      - name: Get Version and Build Number
        id: version
        run: |
          VERSION_LINE=$(grep '^version: ' pubspec.yaml)
          VERSION=$(echo $VERSION_LINE | sed 's/version: //')
          BUILD_NUMBER=$(echo $VERSION | cut -d '+' -f 2)
          echo "build_number=$BUILD_NUMBER" >> $GITHUB_OUTPUT

      - name: Prepare Release Notes
        id: release_notes
        run: |
          CHANGELOG_FILE="fastlane/metadata/android/en-US/changelogs/${{ steps.version.outputs.build_number }}.txt"
          if [ -f "$CHANGELOG_FILE" ]; then
            cat "$CHANGELOG_FILE" > release_notes.md
          else
            echo "Release ${{ github.ref_name }}" > release_notes.md
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: release_notes.md
          files: |
            apks/sample-app-arm64-v8a-${{ github.ref_name }}.apk

  deploy_playstore:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Decode Playstore Secrets
        env:
          PLAYSTORE_JSON_BASE64: ${{ secrets.PLAYSTORE_JSON_BASE64 }}
          KEYSTORE_BASE64: ${{ secrets.ANDROID_PLAYSTORE_KEYSTORE_BASE64 }}
        run: |
          mkdir -p android/fastlane
          echo "$PLAYSTORE_JSON_BASE64" | base64 -d > android/fastlane/supply.json
          echo "$KEYSTORE_BASE64" | base64 -d > android/app/upload-keystore.jks

      - name: Create key.properties
        run: |
          echo "storeFile=upload-keystore.jks" >> android/key.properties
          echo "storePassword=${{ secrets.ANDROID_PLAYSTORE_KEYSTORE_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ANDROID_PLAYSTORE_KEY_ALIAS }}" >> android/key.properties
          echo "keyPassword=${{ secrets.ANDROID_PLAYSTORE_KEY_PASSWORD }}" >> android/key.properties

      - name: Prepare Play Flavor
        run: ./scripts/prepare_flavor.sh play

      - name: Build Play AAB
        run: flutter build appbundle --flavor play --release

      - name: Deploy to Open Testing
        working-directory: android
        run: fastlane open_test
